### ISSUE TITLE
Recaptcha detects automated queries

### ISSUE THREAD

**Issue by krsamue101** [Binit-Dhakal/Google-reCAPTCHA-v3-solver-using-playwright-python#4]
I'm running it on windows
and recaptcha detects automated queries.
how can I solve it? But google don't block solving with images

**Comment by Binit-Dhakal** [comment]
Hello @krsamue101,
Thank you for the issue. Google blocks if we try to use this method multiple times as they know sound ReCaptcha can be used to bypass Recaptcha. There is no reliable solution that I am aware of rather than IP rotation. If you have any I will love to hear that.
And one question, At what rate are you getting blocked for solving with this way? Is it always or sometimes?
Thank you

**Comment by krsamue101** [comment]
always.. :( also i'm not using proxy

**Comment by Binit-Dhakal** [comment]
Ok, that is kind of interesting. I am guessing you have a "low human score" as per google so recognized as the bot(probably you are sending(or have sent) a lot of automated queries from your IP)  but I think that possibility seems kind of rare for the case of always. If you don't have a proxy, I will suggest you use ["protonvpn"](https://protonvpn.com/free-vpn/) to test what the problem is. Protonvpn is free(for VPN in three countries) and is made by the company for privacy enthusiasts people. So you can sign up and take the free tier. 
And try the script again using vpn.
I think that will help us to narrow down what the exact problem might be.
Thank you.

**Comment by krsamue101** [comment]
I tried it with protonvpn. But it worked only 1 time and google detected i'me sending automated queries.

**Comment by Binit-Dhakal** [comment]
Ok, So if it worked once, the script is correct. I think the issue is IP is being ranked as a bot by google(due to multiple automated requests; it is a free tier so multiple people have used it). I don't think we have any option rather than IP rotation. You can use protonvpn to change your IP address time and often or use multiple proxies or you have to rely on captcha solving APIs like 2captcha or anti-captcha(If you are trying to bypass Recaptcha for some project).
Else there is no reliable solution that I am aware of to bypass this.
If you have any further queries please feel free to comment.
Thank you.

**Comment by krsamue101** [comment]
Then, can I use 2captcha on c# playwright?

**Comment by Binit-Dhakal** [comment]
I guess the answer is yes(https://2captcha.com/demo/recaptcha-v2). There is c# support of 2captcha. And it can be used by playwrights. But you need to research about integrating it. 
Suggestion: If you cannot find exact info on how to integrate it with playwright, the internet has a lot of good resources about integration with selenium. You can look into them and write your solution algorithm in playwright.
Thank you
